title: Tho Smooth
email: your-email@example.com
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://cakers.io/tho-smooth-jekyll-theme"
linked_in_url: https://www.linkedin.com/in/chris-akers-1403114
email_address: chris.j.akers@gmail.com
github_url:  https://github.com/chris-j-akers

markdown:           kramdown
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true

